// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwM-3Tef-6RMq5qKgF5XZx8xqGKmLoxKI',
    appId: '1:81096515070:web:9e9c4f3f1b62cc1c2ab4af',
    messagingSenderId: '81096515070',
    projectId: 'livekick',
    authDomain: 'livekick.firebaseapp.com',
    storageBucket: 'livekick.appspot.com',
    measurementId: 'G-JHVRD3YS1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaK64AaO_XnaX4sA42VcQucs38lWaL4ck',
    appId: '1:81096515070:android:d4a4704679cb40d52ab4af',
    messagingSenderId: '81096515070',
    projectId: 'livekick',
    storageBucket: 'livekick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH3tT-6SRbOOhFX1m6DAY1eoR2iz8dAw8',
    appId: '1:81096515070:ios:0eb727448463443a2ab4af',
    messagingSenderId: '81096515070',
    projectId: 'livekick',
    storageBucket: 'livekick.appspot.com',
    iosBundleId: 'com.example.livekick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH3tT-6SRbOOhFX1m6DAY1eoR2iz8dAw8',
    appId: '1:81096515070:ios:0eb727448463443a2ab4af',
    messagingSenderId: '81096515070',
    projectId: 'livekick',
    storageBucket: 'livekick.appspot.com',
    iosBundleId: 'com.example.livekick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwM-3Tef-6RMq5qKgF5XZx8xqGKmLoxKI',
    appId: '1:81096515070:web:808f70c5476748222ab4af',
    messagingSenderId: '81096515070',
    projectId: 'livekick',
    authDomain: 'livekick.firebaseapp.com',
    storageBucket: 'livekick.appspot.com',
    measurementId: 'G-0F0ERTQB14',
  );
}
